name: Build Zip CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@main
      - name: Install dependencies for build (Apt)
        shell: bash
        run: |
          sudo env DEBIAN_FRONTEND=noninteractive apt update -y && \
          sudo env DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends libarchive-tools curl jq tree
      - name: Build Zip x64
        shell: bash
        env:
          ARCH: "x64"
          OUT_ZIP: "Alpine.zip"
        run: |
          make -e
          sha256sum Alpine.zip | tee Alpine.zip.sha256
          ls -la
      - name: Upload a Build Artifact x64
        uses: actions/upload-artifact@main
        with:
          name: Alpine.zip
          path: ./Alpine.zip
      - name: Upload SHA256 Checksum x64
        uses: actions/upload-artifact@main
        with:
          name: Alpine.zip.sha256
          path: ./Alpine.zip.sha256
